spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  datasource:
    url: jdbc:postgresql://localhost:5432/learning
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none # disabled as flyway migrations will be used
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized
  security:
    enabled: true

info:
  app:
    name: LearningPlatform
    version: 0.0.1
    developer: Tomasz

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type: INFO
    org.flywaydb: INFO
    org.thymeleaf: INFO
    org.thymeleaf.templateresolver: INFO
    org.thymeleaf.TemplateEngine: INFO